## 학습목표
1. boolean indexing의 이해

#### Boolean indexing
  - ndarry 인덱싱 시, bool 리스트를 전달하여 True인 경우만 필터링

* 브로드캐스팅을 활용하여 ndarray로 부터 bool list 얻기
 - 예) 짝수인 경우만 찾아보기

In [1]:
import numpy as np

In [38]:
x = np.random.randint(1, 100, size = 10)
print(x)

[20 17 15 97 92  3 48 49 50  2]


In [39]:
even_mask = x % 2 == 0
print(len(x))
print(len(x % 2 == 0))  # 원래 array의 길이와 같다

10
10


- bool 리스트를 인덱스로 전달

In [40]:
x[even_mask]   # 각 인덱스의 값이 TRUE인 경우에만 원래의 값을 반환/ 원하는 값 필터링 가능

array([20, 92, 48, 50,  2])

In [41]:
x[x % 2 == 0]

array([20, 92, 48, 50,  2])

In [42]:
x[x > 30]

array([97, 92, 48, 49, 50])

####  다중조건 사용하기
 - 파이썬 논리 연산지인 and, or, not 키워드 사용 불가
 - & - AND 
 - | - OR 

In [43]:
x[(x % 2 == 0) & (x < 30)]

array([20,  2])

In [44]:
x[(x < 30) | (x > 50)]

array([20, 17, 15, 97, 92,  3,  2])

#### 예제) 2019년 7월 서울 평균기온 데이터
 - 평균기온이 25도를 넘는 날수는?
 - 평균기온이 25를 넘는 날의 평균 기온은?

In [45]:
temp = np.array(
        [23.9, 24.4, 24.1, 25.4, 27.6, 29.7,
         26.7, 25.1, 25.0, 22.7, 21.9, 23.6, 
         24.9, 25.9, 23.8, 24.7, 25.6, 26.9, 
         28.6, 28.0, 25.1, 26.7, 28.1, 26.5, 
         26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

In [52]:
len(temp[temp > 25.0])

21

In [53]:
np.sum(temp > 25.0)  # 25가 넘을 때마다(TRUE = 1) 더함

21

In [54]:
temp[temp > 25.0].mean()

26.857142857142858

In [55]:
np.mean(temp[temp > 25.0])

26.857142857142858