## 학습목표
 1. numpy에서 자주 사용되는 함수들을 사용해보기

In [1]:
import numpy as np

#### numpy documentation
 - [numpy 공식 문서 링크](https://www.numpy.org/devdocs/reference/)
 - numpy에서 제공되는 함수등에 대한 문서

In [5]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.77175695 0.54797205 0.30133656 0.82484554 0.19920235]
 [0.38482085 0.46276828 0.13183361 0.54649161 0.13104267]
 [0.60827452 0.33442488 0.94070492 0.22878679 0.47851162]]


#### 연산 함수
 - add, substract, multiply, divide

In [6]:
np.add(x, y)  # 인덱스가 같은 원소끼리 합. 두 행렬의 shape이 다른 경우 ERROR

array([[ 0.77175695,  1.54797205,  2.30133656,  3.82484554,  4.19920235],
       [ 5.38482085,  6.46276828,  7.13183361,  8.54649161,  9.13104267],
       [10.60827452, 11.33442488, 12.94070492, 13.22878679, 14.47851162]])

#### **ndarray 연산은 차원, shape이 같아야 한다.**

In [7]:
np.subtract(x, y)

array([[-0.77175695,  0.45202795,  1.69866344,  2.17515446,  3.80079765],
       [ 4.61517915,  5.53723172,  6.86816639,  7.45350839,  8.86895733],
       [ 9.39172548, 10.66557512, 11.05929508, 12.77121321, 13.52148838]])

In [10]:
x + y  # 단순 사칙연산자로도 연산이 가능하다.

array([[ 0.77175695,  1.54797205,  2.30133656,  3.82484554,  4.19920235],
       [ 5.38482085,  6.46276828,  7.13183361,  8.54649161,  9.13104267],
       [10.60827452, 11.33442488, 12.94070492, 13.22878679, 14.47851162]])

In [9]:
x - y

array([[-0.77175695,  0.45202795,  1.69866344,  2.17515446,  3.80079765],
       [ 4.61517915,  5.53723172,  6.86816639,  7.45350839,  8.86895733],
       [ 9.39172548, 10.66557512, 11.05929508, 12.77121321, 13.52148838]])

#### 통계 함수
 - 평균, 분산, 중앙, 최대, 최소값 등등 통계 관련된 함수가 내장

In [16]:
y

array([[0.77175695, 0.54797205, 0.30133656, 0.82484554, 0.19920235],
       [0.38482085, 0.46276828, 0.13183361, 0.54649161, 0.13104267],
       [0.60827452, 0.33442488, 0.94070492, 0.22878679, 0.47851162]])

In [14]:
np.mean(y)

0.45951821363291656

In [15]:
y.mean()

0.45951821363291656

In [17]:
np.max(y)

0.9407049184611173

In [18]:
np.min(y)

0.13104266881785143

In [20]:
np.argmax(y)  # 최대값의 인덱스를 구하는 함수

12

In [21]:
np.var(y), np.median(y), np.std(y)

(0.05886067521128503, 0.4627682835570385, 0.24261219097828748)

#### 집계함수
 - 합계(sum), 누적합계(cumsum) : cumulative sum 등등 계산 가능

In [25]:
np.sum(y)

6.892773204493748

In [33]:
np.sum(y, axis = 1)  # 행 방향으로 합

array([2.64511345, 1.65695703, 2.59070273])

In [34]:
sum(y)  # 열 방향으로 합

array([1.76485232, 1.34516521, 1.37387509, 1.60012394, 0.80875664])

In [23]:
np.cumsum(y)

array([0.77175695, 1.319729  , 1.62106556, 2.4459111 , 2.64511345,
       3.0299343 , 3.49270259, 3.6245362 , 4.17102781, 4.30207048,
       4.910345  , 5.24476987, 6.18547479, 6.41426158, 6.8927732 ])

#### any, all 함수
 - any: 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
 - all: 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [36]:
z = np.random.randn(10)
print(z)

[ 0.88403787 -0.62232462  1.60926766 -1.52350118 -0.37320728  1.02432907
  1.19440245  0.50484803  1.00388702  0.98323826]


In [39]:
z > 0

array([ True, False,  True, False, False,  True,  True,  True,  True,
        True])

In [40]:
np.any(z > 0)

True

In [41]:
np.all(z > 0)

False

#### where 함수
 - 조건에 따라 선별적으로 값을 선택 가능
 - 사용 예) 음수인경우는 0, 나머지는 그대로 값을 쓰는 경우

In [42]:
z = np.random.randn(10)
print(z)

[ 0.270952   -0.8831516   0.32333288 -0.07379128 -1.53769956 -0.21127587
 -1.40180475 -0.03740753 -1.23089098  1.09449692]


In [46]:
np.where(z > 0, z, 0)  # where(condition, TRUE, FALSE)

array([0.270952  , 0.        , 0.32333288, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 1.09449692])