### ravel, np.ravel or x.ravel()
- 다차원 배열을 1차원을 변경
- 'order' 파라미터
  - 'C' - row(열) 우선 변경    (default)
  - 'F' - column(행) 우선 변경

In [3]:
import numpy as np

In [13]:
x = np.arange(15).reshape(3, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [14]:
np.ravel(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
temp = x.ravel()
print(temp)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [19]:
temp[0] = 100
print(temp)
print(x)   # ravel 함수는 성능을 위해 원래 값을 유지,
           #ravel의 데이터를 바꾸면 원본 데이터도 변경된다

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
[[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]


In [25]:
x = np.arange(15).reshape(3, 5)
print(x)
np.ravel(x, order = 'F')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([ 0,  5, 10,  1,  6, 11,  2,  7, 12,  3,  8, 13,  4,  9, 14])

### flatten
- 다차원 배열을 1차원으로 변경
- ravel과의 차이점 : copy를 생성하여 변경함(즉 원본 데이터가 아닌 복사본을 반환)
- 'order'파라미터
  - 'C' - row 우선 변경
  - 'F' - column 우선 변경

In [7]:
y = np.arange(15).reshape(3, 5)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [21]:
temp2 = y.flatten()
print(temp2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [23]:
temp2[0] = 100
print(temp2)
print(y)       # ravel 과 달리 복사본을 만들어 저장하므로 원본 데이터 변경 X

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


### reshape 함수
- array의 shape을 다른 차원으로 변경
- 주의할 점은 reshape한 후의 결과의 전체 원소 개수와 이전 개수가 같아야 가능하다.
- ex) 이미지의 경우 기본적으로 2차원 혹은 3차원(RGB)나 트레이닝을 위해 1차원으로 변경하여 사용 한다.

In [28]:
x = np.arange(36)
print(x)
print(x.shape)
print(x.ndim) # number of dimension

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
(36,)
1


In [41]:
y = x.reshape(6, 6)
print(y)
print(y.shape)
print(y.ndim)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
(6, 6)
2


In [33]:
x.reshape(6, -1)   # 앞의 값을 따라감 반대도 가능

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [36]:
x.reshape(3, 11)  # 3 * 11 = 33 이므로 ERROR

ValueError: cannot reshape array of size 36 into shape (3,11)

In [40]:
z = x.reshape(3, 3, 4)
print(z)
print(z.shape)
print(z.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]
(3, 3, 4)
3
